runsy/petz

petz/api/api_forms.lua

Old petz that where captured before their species might get pregnanat may not have the pregnant_count attribute set. Catch this error instead of crashing.

fix crash in on_rightclick when pregnant_count is not set for old petz

---

petz/api/api_breed.lua

Currently, due to an apparent mistake in introducing a null check w/out noting the order of operations, the stats for a baby horse are half the father's stats +/- 1. Adding some parentheses fixes this.

Fix order of operations for computing baby pony stats

---

petz/api/api_breed.lua

Currently, when breeding mountable pets, the stats are either bumped by -1, 0, or 1 all at once. This PR makes the bump independent for each stat.

randomly increase/decrease mountable pet stats independently

---

petz/misc/nodes.lua

If farming (redo) exist, and add jack o lantern, petz add compat alias and not register that node.
alias allow retro compatibility :)

jackolantern farming compat

---

petz/misc/bonemeal.lua

Bonemeal mod has been updated to use group:bone in recipes.
Petz doesn't need to redefine recipes anymore.
I added the ability to convert seamlessly petz:bone <-> bonemal:bone

bonemeal now uses groups for recipes

---

petz/misc/items.lua

use `minetest.is_player` instead of `placer:is_player` in case the placer is nil. Fixes a crash e.g.
```
2022-05-29 12:12:55: ERROR[Main]: ServerError: AsyncErr: Lua: Runtime error from mod '' in callback LuaABM::trigger(): Runtime error from mod '' in callback item_OnPlace(): ...n/worldmods/petz/petz/misc/items.lua:406: attempt to index local 'placer' (a nil value)
2022-05-29 12:12:55: ERROR[Main]: stack traceback:
2022-05-29 12:12:55: ERROR[Main]: 	...n/../worlds/your-land/worldmods/petz/petz/misc/items.lua:406: in function 'after_place_node'
2022-05-29 12:12:55: ERROR[Main]: 	/opt/minetest/bin/../builtin/game/item.lua:267: in function </opt/minetest/bin/../builtin/game/item.lua:146>
2022-05-29 12:12:55: ERROR[Main]: 	[C]: in function 'place_node'
```

fix crash when placing bottled mob via `minetest.place_node`

---

petz/misc/nodes.lua

Seems that something went wrong in your way to solve this issue in this commit: [solved: the recipe for grain_packet conflicts with the recipe for bonemeal:mulch](https://github.com/runsy/petz/commit/f48925a3acf15253db5d6ac8e96060ab827fe3c8)
It does not touch the grain_packet recipe at all, so I just re-open a new PR as it seems you intended to merge fix.

change grain packet recipe not to overlap bonemeal mulch group:seed recipe

---

petz/misc/nodes.lua

Sorry I forgot to remove type="shapeless" when changing grain_packet recipe

Grain Packet: do not use shapeless recipe, sorry

---

petz/misc/lycanthropy.lua
petz/mod.conf

this started out as just an attempt to fail gracefully if another mod removed the werewolf vignette HUD, but then i decided to fix some other issues w/ werewolves while i was poking around.
* check whether the HUD is actually the werewolf vignette before updating or modifying it.
* fixes #42, though not in an ideal manner, because there's nothing like player monoids for player models/textures. however, werewolves are now roughly compatible w/ 3d_armor, wieldview, and skinsdb simultaneously.
* supersedes #139
* fixes an unreported issue, where sometimes wherewolves who log in at night have their model changed and can't eat meat, but don't get the vignette, and don't have their physics updated.
* refactored some code to make clearer the difference between "lycanthropy" (the ability to …

werewolf fixes

---

petz/api/api_throw.lua
petz/mod.conf

* refactored the logic a little to make it more clear, fixed some minor logic errors
* uses the engine's object collision detection instead of raycast
* track the source (player or mob) of a thrown object, in order to work with mechanics such as [PvP Plus](https://github.com/MT-Eurythmia/pvpplus)
* make spiderwebs respect protection
* don't always assume that the face of a node which was hit is the top of the node (pos.y + 1)
i've provided a couple creative-only tools for testing the behavior of grenades and cobwebs. square balls also seem to work just fine.

cleanup throw logic

---

petz/brains/bh_arboreal.lua
petz/brains/helper_functions.lua

I most cases chimps/squirrels ... are not supposed to climb walls or palisades placed by player when they are made out of "group:tree".
[Lumberjack](https://github.com/joe7575/lumberjack) mod check difference between natural trees (those placed at mapgen, or trees grown from sapling) and artificial trees with param1. When param1 == 0 it is supposed to be a tree placed via api.
I added  node itself to petz.node_name_in return values
In petz.check_tree I retrieved the node data for "front"
In petz.is_tree_like I check node.param1 == 0 for "group:tree" so arboreal will not be able to climb tree walls.

Arboreal: climb only if not placed by player

---

petz/misc/lycanthropy.lua

i'm not sure why metadata would exist and not be de-serializable, but this avoids crashing in that case.

fix crash if pre_werewolf_animation is somehow corrupted (fixes #157)

---

petz/brains/bh_breed.lua

Add logic to copy father stats to mother when breeding mountable petz with syringe disabled.

---

petz/api/api_bees.lua
petz/api/api_convert.lua
petz/api/api_horseshoes.lua
petz/api/api_wagon.lua
petz/misc/items.lua
petz/misc/nodes.lua

`minetest.add_entity` and `minetest.add_item` can return `nil` if the creation of the entity fails, which can result in crashes. this adds nil checks to prevent such crashes.

add nil checks after minetest.add_entity and minetest.add_item, where appropriate

---

petz/misc/lycanthropy.lua
petz/petz.conf
petz/settings.lua

currently, the werewolf damage reduction mechanism, which overrides behavior using `minetest.register_on_punchplayer`, breaks compatibility w/ mods like pvpplus, which prevents damage unless both the attacker and the target have pvp enabled. 
this update fixes this by instead using the `minetest.register_on_player_hpchange` callback. while i was doing this, i also added a setting to allow adjusting the werewolf damage reduction amount.

werewolf damage reduction changes

---

petz/misc/lycanthropy.lua

when i was doing updates to the werewolf previously, i accidentally negated the check for hbhunger when preventing players from eating anything other than raw meat. this fixes that.

prevent werewolves from eating raw meat if hbhunger *isn't* installed

---

petz/brains/bh_arboreal.lua

`petz.node_node_name_in` can return `nil`, resulting in a crash:
```
2023-05-14 13:07:16: ERROR[Main]: ServerError: AsyncErr: Lua: Runtime error from mod 'petz' in callback luaentity_Step(): ...netest_live/bin/../mods/petz/petz/brains/bh_arboreal.lua:21: attempt to index local 'node' (a nil value)
2023-05-14 13:07:16: ERROR[Main]: stack traceback:
2023-05-14 13:07:16: ERROR[Main]: ...netest_live/bin/../mods/petz/petz/brains/bh_arboreal.lua:21: in function 'is_tree_like'
2023-05-14 13:07:16: ERROR[Main]: ...netest_live/bin/../mods/petz/petz/brains/bh_arboreal.lua:79: in function 'func'
2023-05-14 13:07:16: ERROR[Main]: .../mt/5.6.1/Minetest_live/bin/../mods/petz/kitz/engine.lua:652: in function 'execute_queues'
2023-05-14 13:07:16: ERROR[Main]: …
```

add nil check to prevent crash when squirrel is near an unloaded block

---

petz/misc/chests.lua

see https://github.com/minetest/minetest_game/pull/3046 for more information.

prevent chest duplication by verifying that an existing node is an open chest when closing it

---

kitz/engine.lua

in the current fall damage calculation, if a petz falls slightly more than the safe distance (say, 6 nodes), it will lose half of its life. this PR correctly scales the damage if the petz falls between the safe and fatal distance.

correctly scale fall damage based on velocity change

---

petz/misc/chests.lua

The message you can set after placing a christmas chest is not escaped properly. (try `]box[0,0;1,1;red` as an example)

fix missing formspec escape
